apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_full_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: "${{ values.storePath }}"
    jujhar.com/project-build: "on the beast"
    backstage.io/techdocs-ref: dir:.
    snyk.io/org-name: ${{ values.app_full_name }}
    snyk.io/project-ids: b6ab231c-a019-4def-a148-4a10a79d6302
  tags:
    - api
    - express
spec:
  type: api
  lifecycle: production
  owner: ${{ values.owner }}
  system: product
