apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: "${{ values.storePath }}"
    jujhar.com/project-build: "on the beast"
    backstage.io/techdocs-ref: dir:.
    snyk.io/org-name: ${{ values.app_full_name }}
    snyk.io/project-ids: b6ab231c-a019-4def-a148-4a10a79d6302
  tags:
    - api
    - express
spec:
  type: openapi
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ parameters.product }}
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://jujhar.com/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
